name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger the pipeline on push to master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify Python version explicitly

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Install Gunicorn
        run: |
          pip install gunicorn  # Install Gunicorn

      - name: Run Flask API with Gunicorn
        run: |
          export FLASK_APP=getdata.py  # Set Flask app to getdata.py
          gunicorn -w 4 getdata:app --bind 0.0.0.0:9001  # Run with Gunicorn server
